name: release

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  goreleaser:
    name: Build on ${{ matrix.distro }} ${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - arch: amd64
            distro: ubuntu18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: 1.17.0
          args: release --rm-dist
        env:
          GOARCH: amd64
          GOOS: linux
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
